<?php

/** @var array $filter */
$filter = $this->filter;

$title = \Air\Crud\Locale::t('All');

if (!empty($filter['title'])) {
  $title = $filter['title'] . ' (' . $title . ')';
}

?>
<div class="btn-group w-100 rounded-4" data-admin-select-submit="true" data-admin-select>
  <button class="btn btn-primary btn-block text-start px-3"
          data-mdb-dropdown-init
          data-mdb-ripple-init
          data-admin-select-title>
  </button>
  <button
    type="button"
    class="btn btn-primary dropdown-toggle dropdown-toggle-split"
    data-mdb-dropdown-init
    data-mdb-ripple-init></button>

  <input name="filter[<?php echo $filter['by']; ?>]"
         value="<?php echo $filter['value']; ?>"
         type="hidden"
         data-admin-select-input/>

  <ul class="dropdown-menu w-100">
    <li>
      <a class="dropdown-item" role="button" data-admin-select-option>
        <?php echo $title; ?>
      </a>
    </li>
    <li>
      <a class="dropdown-item"
         role="button"
         data-value="true"
         data-admin-select-option
         <?php if ($filter['value'] === 'true') : ?>data-selected<?php endif; ?>>
        <i class="fas fa-eye me-1"></i>
        <?php echo $filter['true']; ?>
      </a>
    </li>
    <li>
      <a class="dropdown-item"
         role="button"
         data-value="false"
         data-admin-select-option
         <?php if ($filter['value'] === 'false') : ?>data-selected<?php endif; ?>>
        <i class="fas fa-eye-slash me-1"></i>
        <?php echo $filter['false']; ?>
      </a>
    </li>
  </ul>
</div>