<?php

use Air\Core\Front;
use Air\Form\Element\Storage;
use Air\Type\File;
use Air\Type\RichContent;

/** @var Storage $element */
$element = $this->element;

/** @var array $storageConfig */
$storageConfig = Front::getInstance()->getConfig()['air']['storage'];

/** @var string $name */
$name = $this->name;

/** @var File[] $files */
$files = $this->files;
?>
<input type="hidden" name="<?php echo $name; ?>[type]" value="<?php echo RichContent::TYPE_FILES; ?>">

<div data-admin-form-storage="<?php echo $name; ?>" data-admin-form-storage-multiple="true">

  <textarea class="d-none" name="<?php echo $name; ?>[value]">
    <?php echo json_encode($files, JSON_PRETTY_PRINT); ?>
  </textarea>

  <a class="btn btn-primary btn-block"
     data-admin-form-storage-add
     data-admin-form-storage-add-key="<?php echo $storageConfig['key']; ?>"
     data-admin-form-storage-add-url="<?php echo $storageConfig['url']; ?>"
     data-admin-form-storage-multiple="true">
    <i class="fas fa-plus"></i>
    <?php echo \Air\Crud\Locale::t('Add file'); ?>
  </a>

  <div class="d-flex flex-wrap"
       data-admin-form-storage-list
       data-admin-form-storage-sortable>
    <?php foreach ($files as $file) : ?>
      <div data-admin-file data-admin-file-storage-url="<?php echo $storageConfig['url']; ?>">
        <?php echo json_encode((array)$file, JSON_PRETTY_PRINT); ?>
      </div>
    <?php endforeach; ?>
  </div>
</div>
