<?php

use Air\Type\Quote;
use Air\Type\RichContent;

/** @var string $name */
$name = $this->name;

/** @var Quote $item */
$quote = $this->quote;
?>
<input type="hidden" name="<?php echo $name; ?>[type]" value="<?php echo RichContent::TYPE_QUOTE; ?>"/>

<div class="form-outline bg-body-tertiary" data-mdb-input-init>
  <input type="text"
         class="form-control form-control-lg"
         id="<?php echo $name; ?>[value][author]"
         name="<?php echo $name; ?>[value][author]"
         value="<?php echo htmlspecialchars($quote->author); ?>">
  <label class="form-label" for="<?php echo $name; ?>[value][author]"><?php echo \Air\Crud\Locale::t('Author'); ?></label>
</div>

<div class="form-outline bg-body-tertiary mt-3" data-mdb-input-init>
  <textarea class="form-control"
            rows="2"
            id="<?php echo $name; ?>[value][quote]"
            name="<?php echo $name; ?>[value][quote]"><?php echo $quote->quote; ?></textarea>
  <label class="form-label" for="<?php echo $name; ?>[value][quote]"><?php echo \Air\Crud\Locale::t('Quote'); ?></label>
</div>