<template type="text/html" data-admin-form-doc-background-color-form-template>
  <div class="modal-body">
    <div class="form-outline bg-body-tertiary p-2 pb-1 px-0" data-mdb-input-init>
      <input type="color"
             class="form-control form-control-lg rounded-4"
             value="#ffffff"
             data-admin-form-doc-background-color-form-input
             required>
      <label class="form-label" for="color"><?php echo \Air\Crud\Locale::t('Background color'); ?></label>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-primary btn-lg px-3" data-mdb-ripple-init data-admin-form-doc-background-color-form-apply>
      <i class="fas fa-check me-1"></i> <?php echo \Air\Crud\Locale::t('Apply'); ?>
    </button>
    <button class="btn btn-secondary btn-lg px-3" data-mdb-ripple-init data-mdb-dismiss="modal">
      <i class="fas fa-ban me-1"></i> <?php echo \Air\Crud\Locale::t('Cancel'); ?>
    </button>
  </div>
</template>