<template type="text/html" data-admin-form-doc-page-item-embed-template>
  <div class="item" data-admin-form-doc-page-item="{{id}}" data-resizable data-draggable>
    <iframe class="border-0 w-100 h-100" src="{{src}}"></iframe>
    <div class="position-absolute top-0 bottom-0 start-0 end-0 z-i-1"
         ondblclick="modal.embed('{{src}}')"
         data-admin-contextmenu="{{id}}"></div>
  </div>
  <ul class="dropdown-menu shadow-5-strong overflow-hidden" data-admin-contextmenu-target="{{id}}">
    <li class="p-3 pb-0">
      <?php echo \Air\Crud\Locale::t('Transparent'); ?>
      <div class="range" data-mdb-range-init>
        <input type="range" class="form-range" value="100" data-admin-form-doc-page-item-transparent="{{id}}"/>
      </div>
    </li>
    <li>
      <a class="dropdown-item" role="button" onclick="modal.embed('{{src}}')">
        <i class="fas fa-eye me-1"></i> <?php echo \Air\Crud\Locale::t('View'); ?>
      </a>
    </li>
    <li>
      <a class="dropdown-item" role="button" data-admin-form-doc-page-item-remove="{{id}}">
        <i class="fas fa-ban me-1"></i> <?php echo \Air\Crud\Locale::t('Remove?'); ?>
      </a>
    </li>
  </ul>
</template>