<template type="text/html" data-admin-form-doc-page-item-image-template>
  <div class="item bg-image d-flex justify-content-center align-items-center"
       style="background-image: url('{{thumbnail}}')"
       ondblclick="modal.embed('{{src}}', '', '', '{{mime}}')"
       data-admin-form-doc-page-item="{{id}}"
       data-admin-contextmenu="{{id}}"
       data-resizable
       data-draggable></div>
  <ul class="dropdown-menu shadow-5-strong overflow-hidden" data-admin-contextmenu-target="{{id}}">
    <li class="p-3 pb-0">
      <div class="d-flex justify-content-between align-items-center">
        <div><?php echo \Air\Crud\Locale::t('Transparent'); ?></div>
        <div class="badge badge-primary" data-admin-form-doc-page-item-transparent-label="{{id}}">100</div>
      </div>
      <div class="range" data-mdb-range-init>
        <input type="range" class="form-range" value="100" data-admin-form-doc-page-item-transparent="{{id}}"/>
      </div>
    </li>
    <li>
      <a class="dropdown-item" role="button" onclick="modal.embed('{{src}}', '', '', '{{mime}}')">
        <i class="fas fa-eye me-1"></i> <?php echo \Air\Crud\Locale::t('View'); ?>
      </a>
    </li>
    <li>
      <a class="dropdown-item" role="button" data-admin-form-doc-page-item-remove="{{id}}">
        <i class="fas fa-ban me-1"></i> <?php echo \Air\Crud\Locale::t('Remove?'); ?>
      </a>
    </li>
  </ul>
</template>