<?php

use Air\Crud\Model\Language;
use Air\Form\Element\Model;
use Air\Crud\Locale;

/** @var Model $element */
$element = $this->element;

$value = $element->getValue();
$name = $element->getName();
$parent = $element->getParent();

$hasImage = $element->getModel()->getMeta()->hasProperty('image');
$hasEnabled = $element->getModel()->getMeta()->hasProperty('enabled');
$hasLanguage = $element->getModel()->getMeta()->hasProperty('language');
$hasParent = $element->getModel()->getMeta()->hasProperty($parent ?? '');
?>

<div class="btn-group w-100 rounded-4" data-admin-select>
  <button
    class="btn btn-primary btn-block btn-lg text-start px-3 admin-select-button"
    data-mdb-dropdown-init
    data-mdb-ripple-init
    data-admin-select-title>
  </button>
  <button
    type="button"
    class="btn btn-primary btn-lg dropdown-toggle dropdown-toggle-split"
    data-mdb-dropdown-init
    data-mdb-ripple-init></button>

  <input name="<?php echo $name; ?>" value="<?php echo $value?->id; ?>" type="hidden" data-admin-select-input/>

  <ul class="dropdown-menu w-100 admin-select-searchable overflow-y-auto">
    <li class="d-flex align-items-center gap-2">
      <a class="dropdown-item" role="button" data-admin-select-option>
        <?php echo $element->getLabel(); ?>
      </a>
      <?php if ($hasLanguage) : ?>
        <div class="d-flex gap-2 pe-2">
          <div class="badge badge-primary" role="button" data-admin-select-language-reset>
            <?php echo Locale::t('All'); ?>
          </div>
          <?php foreach (Language::fetchAll() as $language) : ?>
            <div class="badge badge-secondary d-flex align-items-center gap-2" role="button"
                 data-admin-select-language="<?php echo $language->id; ?>">
              <img src="<?php echo $language->image->getSrc(); ?>" style="height: 10px;">
              <span class="lh-1"><?php echo strtoupper($language->key); ?></span>
            </div>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>
    </li>
    <li class="p-2">
      <div class="form-outline" data-mdb-input-init>
        <input type="text" class="form-control" data-admin-select-search/>
        <label class="form-label"><?php echo Locale::t('Search'); ?></label>
      </div>
    </li>
    <?php foreach ($element->getModel()::fetchAll() as $rec) : ?>
      <li>
        <a class="dropdown-item"
           role="button"
           data-value="<?php echo $rec->id; ?>"
           data-admin-select-option
           <?php if ($hasLanguage) : ?>data-admin-select-option-language="<?php echo $rec->language->id; ?>"<?php endif; ?>
           <?php if ($value?->id === $rec->id) : ?>data-selected<?php endif; ?>>
          <div class="d-flex justify-content-between align-items-center">
            <?php if ($hasImage) : ?>
              <div class="admin-select-image bg-image rounded-4 me-3"
                   data-admin-async-image="<?php echo $rec->image?->getSrc(); ?>"></div>
            <?php endif; ?>
            <div
              class="flex-grow-1 text-wrap max-lines-2 pe-3 admin-select-button-title d-flex align-items-center gap-2">
              <?php
              $field = $element->getField();
              if (is_string($field)) {
                if ($hasParent && $rec->{$parent}) {
                  echo $rec->{$parent}->$field . ' › ';
                }
                echo $rec->$field;
              } else if (is_callable($field)) {
                echo $field($rec);
              }
              ?>
            </div>
            <div class="d-flex gap-2">
              <?php if ($hasLanguage && $rec->language?->key) : ?>
                <div class="badge badge-primary d-flex gap-2">
                  <img src="<?php echo $rec->language->image->getSrc(); ?>" style="height: 10px;">
                  <?php echo strtoupper($rec->language->key); ?>
                </div>
              <?php endif; ?>
              <?php if ($hasEnabled) : ?>
                <i
                  class="fas fa-<?php if ($rec->enabled) : ?>check text-success<?php else: ?>ban text-danger<?php endif; ?>"></i>
              <?php endif; ?>
            </div>
          </div>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>
</div>