<?php

use Air\Core\Front;
use Air\Form\Element\Page;

/** @var Page $element */
$element = $this->element;

/** @var array $storageConfig */
$storageConfig = Front::getInstance()->getConfig()['air']['storage'];

$value = $element->getValue();
$jsonValue = $value ? json_encode($value, JSON_PRETTY_PRINT) : '{}';
?>

<div class="admin-form-doc-page"
     data-admin-form-doc-page-element-container="<?php echo $element->getName(); ?>"
     data-admin-form-doc-page-element-storage-url="<?php echo $storageConfig['url']; ?>"
     data-admin-form-doc-page-element-storage-key="<?php echo $storageConfig['key']; ?>">

  <textarea name="<?php echo $element->getName(); ?>"
            style="width: 100%; height: 100px; display: none"
            data-admin-form-doc-page-element-value><?php echo $jsonValue; ?></textarea>

  <?php echo $this->partial('form/element/page/element/container'); ?>
</div>

<?php
if (!Page::$templatesRendered) {
  Page::$templatesRendered = false;

  echo $this->partial('form/element/page/template/file');
  echo $this->partial('form/element/page/template/embed');
  echo $this->partial('form/element/page/template/html');
  echo $this->partial('form/element/page/template/html-form');
  echo $this->partial('form/element/page/template/sorting-layouts');
  echo $this->partial('form/element/page/template/background-color-form');
}
?>
