<?php

use Air\Form\Element\RichContent;

/** @var RichContent $element */
$element = $this->element;
?>
  <div data-admin-form-rich-content-container="<?php echo $element->getName(); ?>">

    <div data-admin-form-rich-content="<?php echo $element->getName(); ?>" class="row gy-3">
      <div class="col-12" data-admin-form-rich-content-element-container-replacement>
        <?php echo $this->partial('form/element/rich-content/toolbar'); ?>
      </div>

      <?php foreach (($element->getValue() ?? []) as $index => $item) : ?>
        <?php $name = $element->getName() . '[' . md5(rand(0, time())) . ']'; ?>

        <div class="col-12" data-admin-form-rich-content-element-container>
          <div class="card bg-body">
            <div class="card-body p-3 d-flex">
              <div class="flex-grow-1">
                <?php if ($item->getType() === \Air\Type\RichContent::TYPE_FILE) : ?>
                  <?php echo $this->partial('form/element/rich-content/element/file', ['name' => $name, 'file' => $item->getValue()]); ?>

                <?php elseif ($item->getType() === \Air\Type\RichContent::TYPE_FILES) : ?>
                  <?php echo $this->partial('form/element/rich-content/element/files', ['name' => $name, 'files' => $item->getValue()]); ?>

                <?php elseif ($item->getType() === \Air\Type\RichContent::TYPE_QUOTE) : ?>
                  <?php echo $this->partial('form/element/rich-content/element/quote', ['name' => $name, 'quote' => $item->getValue()]); ?>

                <?php elseif ($item->getType() === \Air\Type\RichContent::TYPE_TEXT) : ?>
                  <?php echo $this->partial('form/element/rich-content/element/text', ['name' => $name, 'text' => $item->getValue()]); ?>

                <?php elseif ($item->getType() === \Air\Type\RichContent::TYPE_HTML) : ?>
                  <?php echo $this->partial('form/element/rich-content/element/html', ['name' => $name, 'html' => $item->getValue()]); ?>

                <?php elseif ($item->getType() === \Air\Type\RichContent::TYPE_EMBED) : ?>
                  <?php echo $this->partial('form/element/rich-content/element/embed', ['name' => $name, 'embed' => $item->getValue()]); ?>

                <?php endif; ?>
              </div>
              <div class="ms-3">
                <a class="btn btn-danger px-3" data-admin-form-rich-content-element-container-remove>
                  <i class="fas fa-close"></i>
                </a>
              </div>
            </div>
          </div>
        </div>

        <div class="mt-3" data-admin-form-rich-content-element-container-replacement>
          <?php echo $this->partial('form/element/rich-content/toolbar'); ?>
        </div>

      <?php endforeach; ?>
    </div>
  </div>

<?php
echo $this->partial('form/element/rich-content/template/container');
echo $this->partial('form/element/rich-content/template/toolbar');

echo $this->partial('form/element/rich-content/template/file');
echo $this->partial('form/element/rich-content/template/files');
echo $this->partial('form/element/rich-content/template/quote');
echo $this->partial('form/element/rich-content/template/text');
echo $this->partial('form/element/rich-content/template/html');
echo $this->partial('form/element/rich-content/template/embed');
?>