<?php

use Air\Model\Paginator;
use Air\Crud\Locale;

/** @var Paginator $paginator */
$paginator = $this->paginator;

/** @var array $calculation */
$calculation = $paginator->calculate();

/** @var int $next */
$next = $calculation['next'];

/** @var int[] $pages */
$pages = $calculation['pages'];

/** @var int $prev */
$prev = $calculation['prev'];
?>
<div class="row d-flex justify-content-between align-items-center">
  <div class="col">
    <div class="h6 small m-0">
      <?php if ($paginator->count() <= $paginator->getItemsPerPage()) : ?>
        <b><?php echo $paginator->count(); ?></b> <?php echo Locale::t('items'); ?>.
      <?php else: ?>
        <b><?php echo (($paginator->getPage() - 1) * $paginator->getItemsPerPage()) + 1; ?></b> -
        <b><?php $till = $paginator->getPage() * $paginator->getItemsPerPage();
          echo $till > $paginator->count() ? $paginator->count() : $till; ?></b>
        /
        <b><?php echo $paginator->count(); ?></b> <?php echo Locale::t('items'); ?>.
      <?php endif; ?>
    </div>
  </div>
  <div class="col">
    <?php if ($paginator->count() > $paginator->getItemsPerPage()) : ?>
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-end m-0" data-admin-table-paginator>

          <?php if ($prev) : ?>
            <li class="page-item">
              <a class="page-link" data-page="<?php echo $prev; ?>" role="button">
                <i class="fas fa-arrow-left-long"></i>
              </a>
            </li>
          <?php endif; ?>

          <?php foreach ($pages as $page) : ?>
            <li class="page-item <?php if ($page == $paginator->getPage()) : ?>active<?php endif; ?>">
              <a class="page-link" data-page="<?php echo $page; ?>" role="button">
                <?php echo $page; ?>
              </a>
            </li>
          <?php endforeach; ?>

          <?php if ($next) : ?>
            <li class="page-item">
              <a class="page-link" data-page="<?php echo $next; ?>" role="button">
                <i class="fas fa-arrow-right-long"></i>
              </a>
            </li>
          <?php endif; ?>
        </ul>
      </nav>
    <?php endif; ?>
  </div>
</div>

