<?php

use Air\Crud\Model\Admin;
use Air\Form\Element\Hidden;
use Air\Form\Form;

/** @var string $icon */
$icon = $this->icon;

/** @var string $title */
$title = $this->title;

/** @var Admin $admin */
$admin = $this->admin;

/** @var Form $form */
$form = $this->form;
?>

<div class="p-3 position-sticky top-0 z-1 header">
  <div class="card position-sticky w-100">
    <div class="card-body p-3 d-flex justify-content-between align-items-center">
      <h5 class="m-0 p-0">
        <i class="fas fa-<?php echo $icon; ?> me-1"></i>
        <?php echo $title; ?>
      </h5>
      <div class="d-flex">
        <a class="btn btn-secondary ms-2 px-3" data-mdb-ripple-init data-admin-from-manage-back>
          <i class="fa fa-arrow-left me-1"></i>
          <?php echo \Air\Crud\Locale::t('Go back'); ?>
        </a>
        <a class="btn btn-primary ms-2 px-3" data-mdb-ripple-init data-admin-from-manage-save>
          <i class="fa fa-save me-1"></i>
          <?php echo \Air\Crud\Locale::t('Save (CTRL+S)'); ?>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="p-3 pt-0 overflow-hidden overflow-y-auto z-1 content">
  <div class="card">
    <div class="card-body p-3">
      <form data-admin-from-manage>
        <input type="hidden" value="" name="quick-save"/>

        <div data-admin-tab>

          <div class="d-flex mb-2" data-admin-tab-nav>
            <div class="rounded-4 p-3 m-0 me-2 h6 position-relative" role="button" data-mdb-ripple-init>
              <?php echo $title; ?>
              <?php if (count($form->getErrorMessages())) : ?>
                <div class="rounded-pill bg-danger position-absolute end-0 top-0 lh-sm admin-form-tab-has-errors"></div>
              <?php endif; ?>
            </div>
          </div>

          <div class="d-flex w-100" data-admin-tab-content>
            <div class="rounded-4 py-0 px-3 bg-body-secondary w-100">
              <?php foreach ($form->getElements() as $element) : ?>
                <?php if ($element instanceof Hidden) : ?>
                  <?php echo $element; ?>
                <?php else: ?>
                  <div class="py-3"><?php echo $element; ?></div>
                <?php endif; ?>
              <?php endforeach; ?>
            </div>
          </div>

        </div>
      </form>
    </div>
  </div>
</div>