<div class="row mt-5">
  <div class="col-4 offset-4">
    <div class="card alert-danger">
      <div class="card-body p-3">
        <h6 class="p-0 m-0 lead">
          <i class="fas fa-triangle-exclamation me-1"></i>
          <?php echo \Air\Crud\Locale::t('Ooops...'); ?>
        </h6>
        <hr>
        <?php echo \Air\Crud\Locale::t('This page is not permitted for you'); ?>
      </div>
    </div>
  </div>
</div>