<?php

/** @var string $title */

use Air\Core\Front;
use Air\Crud\Model\Language;
use Air\Map;
use Air\Model\ModelAbstract;
use Air\Crud\Locale;

$title = $this->title;

/** @var string $icon */
$icon = $this->icon;

/** @var string $mode */
$mode = $this->mode;

/** @var bool $isSingle */
$isSingle = $this->isSingle;

$filter = $this->filter ?? [];

/** @var bool $manageable */
$manageable = $this->manageable;

/** @var bool $manageableMultiple */
$manageableMultiple = $this->manageableMultiple;

$request = Front::getInstance()->getRequest();

/** @var bool $positioning */
$positioning = $this->positioning;

/** @var bool $isQuickManage */
$isQuickManage = $this->isQuickManage;

/** @var bool $isPrintable */
$isPrintable = $this->printable;

/** @var bool $isSingleControl */
$isSingleControl = $this->isSingleControl;

/** @var bool $isPositioningControl */
$isPositioningControl = $this->isPositioningControl;

/** @var bool $exportable */
$exportable = $this->exportable;
$headerButtons = $this->headerButtons ?? [];

/** @var string $controller */
$controller = $this->controller;

/** @var ModelAbstract $model */
$model = $this->model;

/** @var boolean $isMultipleManage */
$isMultipleManage = $this->isMultipleManage;
?>
<div class="p-3 position-sticky top-0 z-i-1001 header">
  <div class="card position-sticky w-100">
    <div class="card-body p-3 d-flex justify-content-between align-items-center">

      <h5 class="m-0 p-0 flex-shrink-0">
        <?php if ($icon) : ?>
          <i class="fas fa-<?php echo $icon; ?> me-1"></i>
        <?php endif; ?>
        <?php echo $title; ?>
      </h5>

      <div class="d-flex">

        <?php if ($mode === 'manage') : ?>

          <?php if ($model && $model->id && $model->getMeta()->hasProperty('language') && ($model->getMeta()->hasProperty('url') || $isSingle)) : ?>
            <div data-admin-manage-switch-language-quick-manage="<?php echo $isQuickManage ? 'yes' : 'no'; ?>"
                 data-admin-manage-switch-language-controller="<?php echo $controller; ?>"
                 data-admin-manage-switch-language="<?php echo $model->language?->id; ?>">
              <?php
              $cond = $isSingle ? [] : ['url' => $model->url];
              echo script(
                attr: ['type' => 'application/json', 'data-admin-manage-switch-language-map'],
                content: json_encode(Map::execute($model::fetchAll($cond), function (ModelAbstract $m) use ($controller, $isQuickManage) {
                  return [
                    'controller' => $controller,
                    'languageId' => $m->language?->id,
                    'recordId' => $m->id,
                    'isQuickManage' => $isQuickManage
                  ];
                }))); ?>
              <?php echo $this->partial('table/partial/filter/model', ['filter' => [
                'model' => Language::class,
                'by' => 'language',
                'value' => $model->language?->id
              ]]); ?>
            </div>
          <?php endif; ?>

          <?php if (!$isQuickManage && !$isSingle) : ?>
            <a class="btn btn-secondary ms-2 px-3" data-mdb-ripple-init data-admin-from-manage-back>
              <i class="fa fa-arrow-left me-1"></i>
              <?php echo Locale::t('Go back'); ?>
            </a>
          <?php endif; ?>

          <a class="btn btn-primary ms-2 px-3" data-mdb-ripple-init data-admin-from-manage-save>
            <i class="fa fa-save me-1"></i>
            <?php echo Locale::t('Save (CTRL+S)'); ?>
          </a>
        <?php endif; ?>

        <?php if (count($filter)) : ?>
          <a href="<?php echo $this->uri(['controller' => $controller]); ?>" class="btn btn-danger ms-2 px-3"
             data-mdb-ripple-init>
            <i class="fa fa-filter me-1"></i>
            <?php echo Locale::t('Clear filter'); ?>
          </a>
        <?php endif; ?>

        <?php if ($manageable) : ?>
          <a
            href="<?php echo $this->uri(['controller' => $controller, 'action' => 'manage'], ['returnUrl' => $request->getUri()]); ?>"
            class="btn btn-primary ms-2 px-3"
            data-mdb-ripple-init>
            <i class="fas fa-plus me-1"></i>
            <?php echo Locale::t('Add'); ?>
          </a>
        <?php endif; ?>

        <?php if ($manageableMultiple) : ?>
          <a
            data-href="<?php echo $this->uri(['controller' => $controller, 'action' => 'manageMultiple'], $request->getParams()); ?>"
            data-bulk-manage="<?php echo $controller; ?>"
            class="btn btn-primary ms-2 px-3"
            data-mdb-ripple-init>
            <i class="fas fa-edit me-1"></i>
            <?php echo Locale::t('Bulk manage'); ?>
            <span></span>
          </a>
        <?php endif; ?>

        <?php if ($isPrintable) : ?>
          <a class="btn btn-info ms-2 px-3"
             href="<?php echo $this->uri(['controller' => $controller, 'action' => 'print'], $request->getParams()); ?>"
             target="_blank"
             data-force="true"
             data-mdb-ripple-init>
            <i class="fas fa-print me-1"></i>
            <?php echo Locale::t('Print'); ?>
          </a>
        <?php endif; ?>

        <?php if ($positioning && !$isPositioningControl) : ?>
          <a class="btn btn-info ms-2 px-3"
             href="<?php echo $this->uri(['controller' => $controller, 'action' => 'position'], $request->getParams()); ?>"
             data-mdb-ripple-init>
            <i class="fas fa-sort me-1"></i>
            <?php echo Locale::t('Sort'); ?>
          </a>
        <?php endif; ?>

        <?php if ($isPositioningControl) : ?>

          <a class="btn btn-secondary ms-2 px-3" data-mdb-ripple-init data-admin-from-manage-back>
            <i class="fa fa-arrow-left me-1"></i>
            <?php echo Locale::t('Go back'); ?>
          </a>

          <a class="btn btn-primary ms-2 px-3" data-mdb-ripple-init data-admin-from-positioning-save>
            <i class="fa fa-save me-1"></i>
            <?php echo Locale::t('Save (CTRL+S)'); ?>
          </a>

        <?php endif; ?>

        <?php if ($exportable) : ?>
          <a
            href="<?php echo $this->uri(['controller' => $controller, 'action' => 'export'], $request->getParams()); ?>"
            class="btn btn-secondary ms-2 px-3"
            data-mdb-ripple-init
            data-force="true">
            <i class="fas fa-download me-1"></i>
            <?php echo Locale::t('Export'); ?>
          </a>
        <?php endif; ?>

        <?php foreach ($headerButtons as $headerButton) : ?>
          <?php $url = is_array($headerButton['url']) ? $this->uri($headerButton['url'], $headerButton['params'] ?? []) : $headerButton['url']; ?>
          <a class="btn btn-<?php echo $headerButton['style']['color'] ?? 'primary'; ?> ms-2 px-3"
            <?php if ($headerButton['confirm'] ?? false) : ?>
              href="<?php echo $url; ?>"
              data-confirm="<?php echo $headerButton['confirm']; ?>"
            <?php else: ?>
              href="<?php echo $url; ?>"
            <?php endif; ?>
            <?php if ($headerButton['force'] ?? false) : ?>
              data-force="true"
            <?php endif; ?>
             data-mdb-ripple-init>
            <?php if ($headerButton['style']['icon'] ?? false) : ?>
              <i class="fas fa-<?php echo $headerButton['style']['icon']; ?> me-1"></i>
            <?php endif; ?>
            <?php echo $headerButton['title']; ?>
          </a>
        <?php endforeach; ?>

      </div>
    </div>
  </div>
</div>