<?php

use Air\Paginator;

/** @var int $page */
$page = $this->page;

/** @var Paginator $paginator */
$paginator = $this->paginator;

/** @var string $style */
$style = $this->style;
?>

<div class="p-3 overflow-hidden overflow-y-auto z-1 content">
  <form data-admin-table-form>
    <input type="hidden" value="<?php echo $page; ?>" name="page"/>

    <?php echo $this->partial('table/partial/filter'); ?>

    <div class="card">
      <div class="card-body p-3">

        <?php if ($paginator->getFilteredCount()) : ?>

          <div class="row row-gap-4">
            <?php foreach ($paginator->getPageItems() as $icon) : ?>
              <?php $iconTitle = ucfirst(strtolower(str_replace(['_', '-'], ' ', $icon))); ?>
              <div class="col-2">
                <div data-admin-faicon-id="<?php echo $icon; ?>"
                     data-admin-faicon-title="<?php echo $iconTitle; ?>"
                     class="p-2 rounded-3 shadow-2 bg-body-tertiary text-center d-flex gap-2 flex-column"
                     role="button">
                  <?php echo \faIcon(icon: $icon, style: $style, class: 'fs-1 icon p-3'); ?>
                  <div class="small max-lines-1 text-muted">
                    <?php echo $iconTitle; ?>
                  </div>
                </div>
              </div>
            <?php endforeach; ?>
          </div>

          <div class="bg-body p-4 py-3 rounded-3 mt-3">
            <?php echo $this->partial('fa-icon/paginator', ['paginator' => $paginator]); ?>
          </div>

        <?php else: ?>
          <h6 class="m-0 p-0 text-muted"><?php echo \Air\Crud\Locale::t('No records'); ?></h6>
        <?php endif; ?>

      </div>
    </div>
  </form>
</div>