<?php

use Air\Type\Page;

/** @var \Air\Form\Element\Page $element */
$element = $this->element;
$value = $element->getValue();

$transparent = (!$value?->getBackgroundImage() && !$value?->getBackgroundColor()) ? 'transparent' : '';
$css = $value?->asCss() ?? 'width: ' . Page::WIDTH . 'px; height: ' . Page::HEIGHT . 'px';
?>

<div class="card bg-body">
  <div class="card-body p-3">
    <?php echo $this->partial('form/element/page/toolbar'); ?>
    <div class="d-flex">
      <div class="page bg-image rounded mt-3 <?php echo $transparent; ?>"
           style="<?php echo $css; ?>"
           data-admin-form-doc-page>
        <?php foreach (($value?->getItems() ?? []) as $item): ?>
          <?php echo $this->partial('form/element/page/element/' . $item->getType(), [
            'item' => $item
          ]); ?>
        <?php endforeach; ?>
      </div>
      <div class="mt-3 ms-3" data-admin-form-doc-page-sorting-items></div>
    </div>
  </div>
</div>
