<?php

use Air\Type\PageItem;

/** @var PageItem $item */
$item = $this->item;

$id = uniqid();
?>
<div class="item"
     style="<?php echo $item->asCss(); ?>"
     data-admin-form-doc-page-item="<?php echo $id; ?>"
     data-resizable
     data-draggable>

  <iframe class="border-0 w-100 h-100" src="<?php echo $item->getValue(); ?>"></iframe>

  <div class="position-absolute top-0 bottom-0 start-0 end-0 z-i-1"
       ondblclick="modal.embed('<?php echo $item->getValue(); ?>')"
       data-admin-contextmenu="<?php echo $id; ?>"></div>

</div>
<ul class="dropdown-menu shadow-5-strong overflow-hidden" data-admin-contextmenu-target="<?php echo $id; ?>">
  <li class="p-3 pb-0">
    <?php echo \Air\Crud\Locale::t('Transparent'); ?>
    <div class="range" data-mdb-range-init>
      <input type="range"
             class="form-range"
             value="<?php echo $item->getTransparent(); ?>"
             data-admin-form-doc-page-item-transparent="<?php echo $id; ?>"/>
    </div>
  </li>
  <li>
    <a class="dropdown-item" role="button" onclick="modal.embed('<?php echo $item->getValue(); ?>')">
      <i class="fas fa-eye me-1"></i> <?php echo \Air\Crud\Locale::t('View'); ?>
    </a>
  </li>
  <li>
    <a class="dropdown-item" role="button" data-admin-form-doc-page-item-remove="<?php echo $id; ?>">
      <i class="fas fa-ban me-1"></i> <?php echo \Air\Crud\Locale::t('Remove?'); ?>
    </a>
  </li>
</ul>