<?php

use Air\Form\Element\ElementAbstract;
use Air\Form\Element\Hidden;

/** @var ElementAbstract $element */
$element = $this->element;

if ($element instanceof Hidden) {
  echo $this->partial($element->getElementTemplate());
  return;
}
?>
<div class="d-flex align-items-start" data-form-element-container="<?php echo $element->getName(); ?>">
  <div class="me-3 admin-form-label">
    <?php echo $this->partial($element->getLabelTemplate()); ?>
  </div>
  <div class="flex-grow-1">
    <?php echo $this->partial($element->getElementTemplate()); ?>
    <?php echo $this->partial($element->getErrorTemplate()); ?>
  </div>
</div>