<template type="text/html" data-admin-form-rich-content-template="container">

  <div class="mt-3" data-admin-form-rich-content-element-container-replacement>{{toolbar}}</div>

  <div class="col-12" data-admin-form-rich-content-element-container>
    <div class="card bg-body">
      <div class="card-body p-3 d-flex">
        <div class="flex-grow-1">
          {{element}}
        </div>
        <div class="ms-3">
          <a class="btn btn-danger px-3" data-admin-form-rich-content-element-container-remove>
            <i class="fas fa-close"></i>
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-3" data-admin-form-rich-content-element-container-replacement>{{toolbar}}</div>

</template>