<?php

use Air\Type\RichContent;

/** @var \Air\Form\Element\RichContent $element */
$element = $this->element;
$name = $element->getName();
?>
<template type="text/html"
        data-admin-form-rich-content-template-name="<?php echo $name; ?>"
        data-admin-form-rich-content-template="<?php echo RichContent::TYPE_EMBED; ?>">

  <input type="hidden" name="<?php echo $name; ?>[{{name}}][type]" value="<?php echo RichContent::TYPE_EMBED; ?>">

  <div data-admin-form-embed-container="<?php echo $name; ?>[{{name}}]">

    <input type="hidden" name="<?php echo $name; ?>[{{name}}][value]" value="">

    <a class="btn btn-primary btn-block" data-admin-form-embed-add>
      <i class="fas fa-plus me-1"></i> <?php echo \Air\Crud\Locale::t('Type URL'); ?>
    </a>

    <div class="position-relative" data-admin-form-embed-value></div>
  </div>

</template>