<?php

use Air\Type\RichContent;

/** @var \Air\Form\Element\RichContent $element */
$element = $this->element;
$name = $element->getName();
?>
<template type="text/html"
        data-admin-form-rich-content-template-name="<?php echo $name; ?>"
        data-admin-form-rich-content-template="<?php echo RichContent::TYPE_TEXT; ?>">

  <input type="hidden" name="<?php echo $name; ?>[{{name}}][type]" value="<?php echo RichContent::TYPE_TEXT; ?>"/>

  <div class="form-outline bg-body-tertiary" data-mdb-input-init>
    <textarea class="form-control"
              rows="2"
              id="<?php echo $name; ?>[{{name}}][value]"
              name="<?php echo $name; ?>[{{name}}][value]"></textarea>
    <label class="form-label" for="<?php echo $name; ?>[{{name}}]"><?php echo \Air\Crud\Locale::t('Text'); ?></label>
  </div>

</template>